### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by artrag** [agn453/HI-TECH-Z80-C-Cross-Compiler#1]
I've the latest (?) version of this compiler with its manuals (V8 or V7.8pl2, the version number is differ if you look at the IDE or at the read.me with the compiler) . Even if it is released in 2001, I'm not sure about the state of the copyright. 
Do you have info about this aspect ?

**Comment by agn453** [comment]
I am not aware if the later versions with the development environment have been released into public domain.

Microchip Technology is the copyright owner (and they bought the rights from HI-TECH).

The version I have made available was announced on the Facebook Zilog Z80 DIY group by Chris A Hills after he negotiated directly with Microchip Technology.  The license file has the details of the terms for this release.

**Comment by artrag** [comment]
Should you need it let me know

**Comment by agn453** [comment]
I have a copy of the HI-TECH Z80 C V7.6 development cross compiler for MS-DOS.  I know the compiler for this version corrects some code generation issues seen on the native CP/M v3.09 - however, it introduces others (e.g. it won’t compile the c309-11.c compiler front end).  Phillip Stevens pointed me to the benchmarks at the z88dk repository.  If you’re happy to share it with me then send the details or an attachment to my e-mail agn453 at gmail dot com. Thanks.

**Comment by artrag** [comment]
You have an email
